// Generated by export.py using data in metadata.json

#if !__VS_SYSTEM

banked(sound_test_bank.musictext.data.0) const char musicSoundTestString00[15] = "STAY INSIDE ME";
banked(sound_test_bank.musictext.data.1) const char musicSoundTestString01[13] = "TIME MACHINE";
banked(sound_test_bank.musictext.data.2) const char musicSoundTestString02[16] = "SCHEMING WEASEL";
banked(sound_test_bank.musictext.data.3) const char musicSoundTestString03[12] = "DESERT CITY";
banked(sound_test_bank.musictext.data.4) const char musicSoundTestString04[11] = "MENU THEME";
banked(sound_test_bank.musictext.data.5) const char musicSoundTestString05[13] = "OCULARNEBULA";
banked(sound_test_bank.musictext.data.6) const char musicSoundTestString06[11] = "WATERFLAME";
banked(sound_test_bank.musictext.data.7) const char musicSoundTestString07[14] = "KEVIN MACLEOD";
banked(sound_test_bank.musictext.data.8) const char musicSoundTestString08[10] = "idfk lmao";
banked(sound_test_bank.musictext.data.9) const char musicSoundTestString09[ 7] = "RobTop";


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsUpper[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsLower[] = {
	musicSoundTestString00,
	musicSoundTestString01,
	musicSoundTestString02,
	musicSoundTestString03,
	musicSoundTestString04,
};


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsOriginalArtist[] = {
	musicSoundTestString05,
	musicSoundTestString06,
	musicSoundTestString07,
	musicSoundTestString08,
	musicSoundTestString09,
};


#else

const char* const xbgmtextsUpper[] = {};
const u8 xbgmtextsUpperSize[] = {};
const char* const xbgmtextsLower[] = {};
const u8 xbgmtextsLowerSize[] = {};
const char* const xbgmtextsOriginalArtist[] = {};
const u8 xbgmtextsOriginalArtistSize[] = {};

#endif




#if !__VS_SYSTEM

banked(sound_test_bank.musictext.index) const u8 xbgmlookuptable[] = {
	song_stay_inside_me,
	song_time_machine,
	song_scheming_weasel,
	song_desert_city,
	song_menu_theme,
};

#else

banked(sound_test_bank.musictext.index) const u8 xbgmlookuptable[] = {
};

#endif
