; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash EPSM:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_epsm:=music_data_famidash_epsm

music_data_famidash_epsm:
	.byte 6
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : Desert City
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	.endif
	.word 176,146
; 01 : Menu Theme
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	.endif
	.word 262,218
; 02 : Scheming Weasel
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song2ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song2ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song2ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song2ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song2ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song2ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song2ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song2ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song2ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song2ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song2ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song2ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song2ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song2ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song2ch19
	.endif
	.word 335,279
; 03 : Stay Inside Me
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song3ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song3ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song3ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song3ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song3ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song3ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song3ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song3ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song3ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song3ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song3ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song3ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song3ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song3ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song3ch19
	.endif
	.word 262,218
; 04 : Time Machine
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song4ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song4ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song4ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song4ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song4ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song4ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song4ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song4ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song4ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song4ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song4ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song4ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song4ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song4ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song4ch19
	.endif
	.word 290,242

.export music_data_famidash_epsm
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env21,@env4,@env13,@env0 ; 00 : SIM Kick (DMC)
	.word @env15,@env4,@env13,@env0 ; 01 : VEH2 Houseloops - 060 (DMC)
	.word @env5,@env2,@env13,@env0 ; 02 : SIM VEH2_Fill_Ins_-_34 (DMC)
	.word @env12,@env14,@env13,@env0 ; 03 : time machine snare (DMC)

@instruments_exp:
	.word @env11, @env10, @env0 ; 00 : epsm hihat (PSG)
	.word @env16, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch0
	.word @env7, @env10, @env0 ; 01 : epsm open ding (PSG)
	.word @env16, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch1
	.word @env1, @env10, @env0 ; 02 : 001 SEUT - Hi Hat (PSG)
	.word @env16, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch4
	.word @env8, @env10, @env0 ; 03 : D2 HH2-015 (PSG)
	.word @env16, @env9
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch6
	.word @env17, @env10, @env0 ; 04 : 006 SEUT - Hi Hat (PSG)
	.word @env16, @env18
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch7
	.word @env6, @env10, @env0 ; 05 : SIM ding 2 (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch8
	.word @env6, @env10, @env0 ; 06 : epsm noise (PSG)
	.word @env16, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch9
	.word @env6, @env10, @env0 ; 07 : sine decay (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch10
	.word @env6, @env10, @env0 ; 08 : SIM Synth (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch11
	.word @env3, @env10, @env0 ; 09 : 007 SEUT - Hi Hat (PSG)
	.word @env16, @env20
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch12
	.word @env6, @env10, @env0 ; 0a : SIM practice thingy (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch13
	.word @env6, @env10, @env0 ; 0b : Desert guitar (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch14
	.word @env6, @env10, @env0 ; 0c : TM flute (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch15
	.word @env6, @env10, @env0 ; 0d : Scheme whateverthefuck (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch16
	.word @env6, @env10, @env0 ; 0e : TM bass 1 (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch17
	.word @env6, @env10, @env0 ; 0f : TM bass 2 (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch18
	.word @env6, @env10, @env0 ; 10 : Desert bass (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch19
	.word @env6, @env10, @env0 ; 11 : SIM Bass (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch20
	.word @env6, @env10, @env0 ; 12 : Scheme wind thingy (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch21
	.word @env6, @env10, @env0 ; 13 : Scheme Bass (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch22
	.word @env6, @env10, @env0 ; 14 : blank: epsm
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch23
	.word @env6, @env10, @env0 ; 15 : funny desert thingy (FM)
	.word @env19, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch24
	.word @env6, @env10, @env0 ; 16 : time machine synth (PSG)
	.word @env19, @env10
	.byte $00, $80
	.word 4000
	.word @instrument_epsm_extra_patch26

@instrument_epsm_extra_patch0:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch1:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch4:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch6:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch7:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch8:
	.byte $33,$c0,$04,$1f,$11,$00,$ff,$00,$02,$1f,$0f,$00,$86,$00,$00,$1f,$00,$00,$07,$00,$02,$1f,$11,$0d,$27,$00,$1e,$20,$7f,$0d,$00
@instrument_epsm_extra_patch9:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch10:
	.byte $07,$c0,$02,$1f,$00,$0c,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$09,$7f,$7f,$7f,$00
@instrument_epsm_extra_patch11:
	.byte $3a,$c0,$02,$1f,$00,$0b,$07,$00,$02,$1f,$10,$00,$47,$00,$02,$1f,$00,$00,$07,$00,$02,$1f,$0e,$11,$37,$00,$1c,$13,$35,$09,$00
@instrument_epsm_extra_patch12:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch13:
	.byte $2c,$c0,$08,$1f,$18,$00,$ff,$00,$02,$1f,$0f,$00,$86,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$2c,$0d,$7f,$7f,$00
@instrument_epsm_extra_patch14:
	.byte $23,$c0,$01,$1f,$17,$0a,$57,$00,$01,$1f,$00,$00,$07,$00,$01,$1f,$00,$00,$07,$00,$01,$1f,$00,$0d,$07,$00,$05,$25,$20,$11,$00
@instrument_epsm_extra_patch15:
	.byte $2d,$c0,$01,$1f,$00,$00,$01,$00,$71,$0f,$00,$00,$05,$00,$71,$1f,$00,$00,$07,$00,$31,$1f,$00,$00,$05,$00,$1f,$12,$7f,$1f,$00
@instrument_epsm_extra_patch16:
	.byte $34,$c0,$01,$1f,$00,$00,$f0,$00,$01,$12,$0d,$00,$28,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$1b,$0e,$7f,$7f,$00
@instrument_epsm_extra_patch17:
	.byte $30,$c0,$04,$1f,$00,$11,$07,$00,$03,$1f,$00,$0d,$07,$00,$00,$1f,$00,$0c,$07,$00,$01,$1f,$00,$09,$07,$00,$15,$2f,$18,$10,$00
@instrument_epsm_extra_patch18:
	.byte $28,$c0,$05,$1f,$00,$0b,$07,$00,$03,$1f,$00,$0d,$07,$00,$00,$1f,$00,$0c,$07,$00,$01,$1f,$0c,$1f,$1f,$00,$18,$2a,$16,$0e,$00
@instrument_epsm_extra_patch19:
	.byte $0b,$c0,$00,$1f,$15,$0a,$57,$00,$01,$1f,$00,$00,$07,$00,$01,$1f,$00,$00,$07,$00,$01,$1f,$00,$0c,$07,$00,$05,$25,$7f,$11,$00
@instrument_epsm_extra_patch20:
	.byte $3a,$c0,$00,$1f,$0d,$00,$30,$00,$01,$1f,$00,$00,$07,$00,$04,$1f,$00,$00,$07,$00,$01,$13,$00,$00,$07,$00,$1d,$7f,$39,$0d,$00
@instrument_epsm_extra_patch21:
	.byte $03,$c0,$01,$1f,$0f,$00,$1b,$00,$02,$1f,$1f,$00,$0b,$00,$02,$1f,$1f,$03,$0a,$00,$01,$15,$04,$00,$f9,$00,$28,$21,$28,$0e,$00
@instrument_epsm_extra_patch22:
	.byte $33,$c0,$41,$1f,$0f,$07,$10,$00,$71,$1f,$09,$00,$f0,$00,$01,$1f,$10,$01,$60,$00,$41,$1f,$0b,$0c,$27,$00,$21,$1c,$27,$0d,$00
@instrument_epsm_extra_patch23:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch24:
	.byte $33,$c0,$41,$1f,$0f,$07,$10,$00,$71,$1f,$09,$00,$f0,$00,$01,$1f,$10,$01,$60,$00,$41,$1f,$13,$0e,$47,$00,$21,$1c,$27,$0d,$00
@instrument_epsm_extra_patch26:
	.byte $34,$c0,$00,$1f,$00,$00,$08,$00,$00,$1f,$00,$00,$07,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$07,$10,$7f,$7f,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cd,$cc,$cc,$ca,$c8,$c4,$c0,$00,$07
@env2:
	.byte $b7,$bd,$00,$01
@env3:
	.byte $00,$ce,$c0,$00,$02
@env4:
	.byte $b8,$be,$00,$01
@env5:
	.byte $00,$c5,$c2,$c0,$00,$03
@env6:
	.byte $00,$cf,$7f,$00,$02
@env7:
	.byte $00,$ce,$cd,$cd,$cc,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$11
@env8:
	.byte $00,$ce,$cd,$c0,$00,$03
@env9:
	.byte $c8,$c2,$00,$01
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $00,$cf,$ce,$cc,$c0,$00,$04
@env12:
	.byte $00,$c9,$c6,$c4,$c2,$c1,$c0,$00,$06
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $b6,$ba,$00,$01
@env15:
	.byte $00,$c8,$c2,$c1,$c0,$00,$04
@env16:
	.byte $c1,$7f,$00,$00
@env17:
	.byte $00,$ce,$cd,$cd,$c0,$00,$04
@env18:
	.byte $d6,$c8,$00,$01
@env19:
	.byte $c8,$7f,$00,$00
@env20:
	.byte $cb,$7f,$00,$00
@env21:
	.byte $00,$c9,$c4,$c1,$c0,$00,$04

@samples:
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$42,$0f,$00,$00 ; 00 023 SEUT - Kick (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$24,$0f,$40,$00 ; 01 Drums (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$0f,$40,$00 ; 02 practice kick (Pitch:15)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$1c,$0f,$40,$00 ; 03 VEH2 Houseloops  (Pitch:15)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0e,$00,$00 ; 04 VEH2_Fill_Ins_-_ (Pitch:14)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0f,$00,$00 ; 05 VEH2_Fill_Ins_-_ (Pitch:15)

@song0ch0:
	.byte $46, $03
@song0ch0loop:
@song0ref4:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $41, $0c
	.word @song0ref4
	.byte $bf, $bf, $bf, $bf, $42
	.word @song0ch0loop
@song0ch19:
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch15:
@song0ch14:
@song0ch13:
@song0ch12:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
@song0ch3:
@song0ch2:
@song0ch1:
@song0ch1loop:
	.byte $41, $0c
	.word @song0ref4
	.byte $41, $0c
	.word @song0ref4
	.byte $bf, $bf, $bf, $bf, $42
	.word @song0ch1loop
@song0ch8:
@song0ch8loop:
	.byte $7a, $a0
@song0ref57:
	.byte $1e, $8d, $7e, $1e, $a9, $79, $1e, $81, $7a, $1e, $8d, $7e, $1e, $a9, $79, $1e, $81, $7a
	.byte $41, $0c
	.word @song0ref57
	.byte $7a
	.byte $41, $0c
	.word @song0ref57
	.byte $7a
	.byte $41, $0c
	.word @song0ref57
	.byte $7a
	.byte $41, $0c
	.word @song0ref57
@song0ref90:
	.byte $7a, $1e, $8d, $7e, $1e, $9d, $7b, $20, $81, $79, $21, $81, $7b, $23, $81, $7d, $25, $81
	.byte $41, $0c
	.word @song0ref90
	.byte $7a
	.byte $41, $0c
	.word @song0ref57
	.byte $7a
	.byte $41, $0c
	.word @song0ref57
@song0ref119:
	.byte $7a, $1c, $8d, $7e, $1c, $a9, $79, $1c, $81, $7a, $1c, $8d, $7e, $1c, $a9, $79, $1c, $81
	.byte $41, $0c
	.word @song0ref119
	.byte $41, $0c
	.word @song0ref90
	.byte $41, $0c
	.word @song0ref90
	.byte $41, $0c
	.word @song0ref90
	.byte $41, $0c
	.word @song0ref90
	.byte $7a, $1e, $8d, $7e, $1e, $9d, $7b, $20, $81, $5c, $81, $21, $85, $7e, $1e, $bd, $00, $bd, $bf, $42
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
	.byte $8b, $aa
@song0ref177:
	.byte $25, $8d, $25, $8d, $25, $85, $25, $81, $25, $85, $8b, $25, $8d, $25, $8d, $25, $85, $25, $81, $25, $85, $8b
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $16
	.word @song0ref177
	.byte $41, $15
	.word @song0ref177
	.byte $42
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $bf, $bf, $bf, $bf, $7f, $96, $25, $95, $25, $85, $25, $9d, $9b, $26, $8d, $23, $91, $bf, $b9, $47, $02, $76, $25, $81
	.byte $47, $00, $7c, $25, $7f, $25, $95, $25, $85, $25, $9d, $9b, $26, $8d, $23, $91, $87, $25, $b5, $00, $b5, $28, $85, $97
	.byte $26, $a5, $bf, $28, $b5, $26, $85, $bf, $28, $b5, $26, $85, $bf, $21, $bd, $bf, $00, $bd, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $42
	.word @song0ch10loop
@song0ch11:
@song0ch11loop:
	.byte $bf, $bf, $bf, $bf, $00, $89, $7f, $96
@song0ref327:
	.byte $1e, $89, $00, $81, $26, $a1, $97, $25, $85, $25, $9d, $22, $bd, $bb, $47, $01, $79, $25, $81, $00, $89, $7f
	.byte $41, $0d
	.word @song0ref327
	.byte $bf, $28, $bd, $25, $bd, $00, $bd, $25, $bd, $00, $bd, $87, $25, $b5, $00, $bd, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $42
	.word @song0ch11loop
@song1ch0:
	.byte $46, $06
@song1ch0loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song1ch0loop
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch13:
@song1ch12:
@song1ch7:
@song1ch6:
@song1ch5:
@song1ch4:
@song1ch3:
@song1ch2:
@song1ch1:
@song1ch1loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song1ch1loop
@song1ch8:
@song1ch8loop:
	.byte $8e
@song1ref35:
	.byte $0d, $85, $01, $95, $14, $85, $08, $95, $12, $85, $06, $95, $10, $85, $04, $85, $0f, $85, $03, $85
	.byte $41, $14
	.word @song1ref35
	.byte $41, $14
	.word @song1ref35
	.byte $00, $fd, $42
	.word @song1ch8loop
@song1ch9:
@song1ch9loop:
	.byte $81, $8e
@song1ref69:
	.byte $0d, $85, $0d, $95, $14, $85, $14, $95, $12, $85, $12, $95, $10, $85, $10, $85, $0f, $85, $0f, $85
	.byte $41, $13
	.word @song1ref69
	.byte $83, $81
	.byte $41, $14
	.word @song1ref69
	.byte $00, $fb, $42
	.word @song1ch9loop
@song1ch10:
@song1ch10loop:
	.byte $83, $8e
@song1ref105:
	.byte $19, $85, $0d, $95, $20, $85, $14, $95, $1e, $85, $12, $95, $1c, $85, $10, $8d, $0f, $85
	.byte $41, $11
	.word @song1ref105
	.byte $81, $83
	.byte $41, $12
	.word @song1ref105
	.byte $00, $f9, $42
	.word @song1ch10loop
@song1ch11:
@song1ch11loop:
	.byte $85, $8e
@song1ref139:
	.byte $0d, $85, $25, $95, $14, $85, $2c, $95, $12, $85, $2a, $95, $10, $85, $28, $95
	.byte $41, $0f
	.word @song1ref139
	.byte $8f, $85
	.byte $41, $10
	.word @song1ref139
	.byte $00, $f7, $42
	.word @song1ch11loop
@song2ch19:
@song2ch18:
@song2ch17:
@song2ch16:
@song2ch15:
@song2ch14:
@song2ch13:
@song2ch12:
@song2ch7:
@song2ch6:
@song2ch4:
@song2ch3:
@song2ch1:
@song2ch0:
@song2ch0loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song2ch0loop
@song2ch2:
	.byte $46, $06
@song2ch2loop:
@song2ref37:
	.byte $46, $08, $83, $46, $04, $83, $46, $08, $83, $46, $04, $83, $46, $08, $83, $46, $04, $83, $46, $08, $83, $46, $04, $83
	.byte $46, $08, $83, $46, $04, $83, $46, $08, $83, $46, $04, $83
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $41, $0c
	.word @song2ref37
	.byte $46, $08, $83, $46, $04, $83, $46, $08, $83, $46, $04, $83, $ff, $ff, $ff, $ff, $ff, $42
	.word @song2ch2loop
@song2ch5:
@song2ch5loop:
	.byte $ff, $ff, $ff, $97, $7e, $51, $fa, $60, $a8, $40, $55, $85, $7e, $51, $fa, $60, $40, $55, $85, $7e, $51, $fa, $60, $40
	.byte $56, $85, $7e, $51, $fa, $00, $40, $55, $8d, $00, $bd, $97, $7e, $51, $fa, $60, $40, $55, $85, $7e, $51, $fa, $60, $40
	.byte $55, $85, $7e, $51, $fa, $60, $40, $56, $85, $7e, $51, $fa, $00, $40, $55, $8d, $00, $a5, $7e, $51, $fa, $60, $40, $50
	.byte $85, $7e, $51, $fa, $00, $40, $57, $8d
@song2ref258:
	.byte $00, $85, $7e, $51, $fa, $00, $40, $55, $8d, $7e, $51, $fa, $00, $40, $55, $8d, $7e, $51, $fa, $00, $40, $55, $8d, $7e
	.byte $51, $fa, $00, $40, $55, $8d, $7e, $51, $fa, $60, $40, $4e, $85, $7e, $51, $fa, $00, $40, $55, $8d, $00, $85, $7e, $51
	.byte $fa, $00, $40, $55, $8d, $00, $85
	.byte $41, $14
	.word @song2ref258
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song2ch5loop
@song2ch8:
@song2ch8loop:
	.byte $a6
@song2ref330:
	.byte $0d, $85, $5c, $8d, $08, $81, $5c, $81, $0d, $85, $5c, $8d, $08, $81, $5c, $81
	.byte $41, $0b
	.word @song2ref330
	.byte $95
	.byte $41, $10
	.word @song2ref330
@song2ref353:
	.byte $12, $85, $5c, $8d, $14, $81, $5c, $81, $0d, $85, $5c, $95
	.byte $41, $10
	.word @song2ref330
	.byte $41, $0c
	.word @song2ref353
@song2ref371:
	.byte $12, $85, $5c, $8d, $0d, $81, $5c, $81, $12, $85, $5c, $8d, $0d, $81, $5c, $81
	.byte $41, $0b
	.word @song2ref371
	.byte $95
	.byte $41, $10
	.word @song2ref371
	.byte $12, $85, $5c, $8d, $0f, $81, $5c, $81, $14, $85, $5c, $95
	.byte $41, $10
	.word @song2ref330
	.byte $41, $0c
	.word @song2ref353
	.byte $41, $10
	.word @song2ref330
	.byte $41, $0c
	.word @song2ref353
	.byte $14, $85, $5c, $ad, $0f, $85, $14, $85, $5c, $ad, $0f, $85, $14, $85, $5c, $ad, $14, $85, $15, $5c, $bb
	.byte $41, $10
	.word @song2ref330
	.byte $41, $0c
	.word @song2ref353
	.byte $41, $10
	.word @song2ref330
	.byte $41, $0c
	.word @song2ref353
	.byte $00, $fd, $ff, $ff, $ff, $ff, $42
	.word @song2ch8loop
@song2ch9:
@song2ch9loop:
	.byte $87, $9a
@song2ref463:
	.byte $1c, $5c, $83, $1c, $5c, $83, $1c, $5c, $8b, $1c, $5c, $83, $1c, $5c, $83, $1c, $5c, $8b, $1c, $5c, $83, $1c, $5c, $83
	.byte $1c, $5c, $8b, $1c, $85, $1c, $5c, $8b, $87
	.byte $41, $12
	.word @song2ref463
@song2ref499:
	.byte $1e, $5c, $83, $1e, $5c, $83, $1e, $5c, $8b, $1c, $5c, $83, $1c, $5c, $83, $1c, $5c, $83, $87
	.byte $41, $12
	.word @song2ref463
	.byte $41, $0e
	.word @song2ref499
	.byte $8b
@song2ref525:
	.byte $87
@song2ref526:
	.byte $1e, $5c, $83, $1e, $5c, $83, $1e, $5c, $8b, $1e, $5c, $83, $1e, $5c, $83, $1e, $5c, $8b
	.byte $41, $11
	.word @song2ref526
	.byte $83
	.byte $41, $13
	.word @song2ref525
	.byte $1e, $5c, $83, $1e, $5c, $83, $1e, $5c, $8b, $1b, $5c, $83, $1b, $5c, $83, $1b, $5c, $83, $87
	.byte $41, $12
	.word @song2ref463
	.byte $41, $13
	.word @song2ref499
	.byte $41, $12
	.word @song2ref463
	.byte $41, $0e
	.word @song2ref499
	.byte $8b, $87
@song2ref584:
	.byte $17, $5c, $83, $17, $5c, $83, $18, $85, $17, $5c, $83, $17, $5c, $83, $17, $5c, $8b, $17, $5c, $83
	.byte $41, $14
	.word @song2ref584
	.byte $41, $10
	.word @song2ref584
	.byte $83, $17, $85, $18, $5c, $83, $18, $5c, $83, $18, $5c, $83, $18, $5c, $83, $18, $85, $17, $5c, $83, $18, $5c, $83, $17
	.byte $5c, $83, $00, $85
	.byte $41, $12
	.word @song2ref463
	.byte $41, $13
	.word @song2ref499
	.byte $41, $12
	.word @song2ref463
	.byte $41, $0e
	.word @song2ref499
	.byte $8b, $87, $00, $f5, $ff, $ff, $ff, $ff, $42
	.word @song2ch9loop
@song2ch10:
@song2ch10loop:
	.byte $87, $9a
@song2ref664:
	.byte $20, $5c, $83, $20, $5c, $83, $20, $5c, $8b, $20, $5c, $83, $20, $5c, $83, $20, $5c, $8b, $20, $5c, $83, $20, $5c, $83
	.byte $20, $5c, $8b, $1f, $85, $20, $5c, $8b, $87
	.byte $41, $12
	.word @song2ref664
@song2ref700:
	.byte $21, $5c, $83, $21, $5c, $83, $21, $5c, $8b, $20, $5c, $83, $20, $5c, $83, $20, $5c, $83, $87
	.byte $41, $12
	.word @song2ref664
	.byte $41, $0e
	.word @song2ref700
	.byte $8b
@song2ref726:
	.byte $87
@song2ref727:
	.byte $21, $5c, $83, $21, $5c, $83, $21, $5c, $8b, $21, $5c, $83, $21, $5c, $83, $21, $5c, $8b
	.byte $41, $11
	.word @song2ref727
	.byte $83
	.byte $41, $13
	.word @song2ref726
	.byte $21, $5c, $83, $21, $5c, $83, $1f, $5c, $8b, $21, $5c, $83, $21, $5c, $83, $21, $5c, $83, $87
	.byte $41, $12
	.word @song2ref664
	.byte $41, $13
	.word @song2ref700
	.byte $41, $12
	.word @song2ref664
	.byte $41, $0e
	.word @song2ref700
	.byte $8b, $87, $20, $5c, $83, $20, $5c, $83, $21, $85
	.byte $41, $11
	.word @song2ref664
	.byte $83, $21, $85
	.byte $41, $11
	.word @song2ref664
	.byte $83, $21, $85, $20, $5c, $83, $20, $5c, $83, $20, $5c, $83, $20, $85, $21, $5c, $83, $21, $5c, $83, $21, $5c, $83, $21
	.byte $5c, $83, $21, $85, $21, $5c, $83, $21, $5c, $83, $21, $5c, $83, $00, $85
	.byte $41, $12
	.word @song2ref664
	.byte $41, $13
	.word @song2ref700
	.byte $41, $12
	.word @song2ref664
	.byte $41, $0e
	.word @song2ref700
	.byte $8b, $87, $00, $f5, $ff, $ff, $ff, $ff, $42
	.word @song2ch10loop
@song2ch11:
@song2ch11loop:
	.byte $ff, $a4
@song2ref867:
	.byte $25, $81, $27, $81, $28, $5c, $2a, $81, $2c, $5c, $2d, $81, $2c, $5c, $2b, $81, $2c, $81, $2d, $81, $2c, $5c, $2a, $81
	.byte $28, $5c, $27, $81, $25, $81, $20, $81, $21, $81, $5c, $91, $25, $81, $23, $21, $20, $81, $5c, $99
	.byte $41, $2c
	.word @song2ref867
@song2ref914:
	.byte $2a, $81, $29, $5c, $2a, $81, $2c, $5c, $2d, $81, $5c, $a9
	.byte $41, $0b
	.word @song2ref914
	.byte $81, $31, $81, $5c, $81, $2c, $8d, $2d, $81, $5c, $89
	.byte $41, $0c
	.word @song2ref914
	.byte $41, $0b
	.word @song2ref914
	.byte $81, $2a, $81, $5c, $81, $2c, $8d, $27, $81, $5c, $89
	.byte $41, $2c
	.word @song2ref867
	.byte $41, $2c
	.word @song2ref867
	.byte $00, $fd, $ff
	.byte $41, $2c
	.word @song2ref867
	.byte $41, $2c
	.word @song2ref867
	.byte $00, $fd, $ff, $ff, $ff, $ff, $42
	.word @song2ch11loop
@song3ch0:
	.byte $46, $03
@song3ch0loop:
@song3ref4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $ff, $ff, $ff, $ff, $87, $42
	.word @song3ch0loop
@song3ch19:
@song3ch18:
@song3ch17:
@song3ch16:
@song3ch15:
@song3ch14:
@song3ch2:
@song3ch1:
@song3ch1loop:
	.byte $41, $1d
	.word @song3ref4
	.byte $42
	.word @song3ch1loop
@song3ch3:
@song3ch3loop:
	.byte $80, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25
	.byte $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25
	.byte $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25
@song3ref109:
	.byte $9d, $84, $25, $85, $24, $85, $25, $81, $25, $81, $24, $81, $25, $81
@song3ref123:
	.byte $80, $25, $8d, $82, $25, $89, $84, $25, $81, $80, $25, $8d, $82, $25, $8d, $80, $25, $8d, $82, $25, $89, $84, $25, $81
	.byte $80, $25, $81, $84, $25, $89, $82, $25, $8d, $80, $25, $8d, $82, $25, $89, $84, $25, $81, $80, $25, $8d, $82, $25, $8d
	.byte $80, $25, $8d, $82, $25, $89, $84, $25, $81, $80, $25, $81, $84, $25, $89, $82, $25, $8d
	.byte $41, $2c
	.word @song3ref123
	.byte $41, $2c
	.word @song3ref123
	.byte $41, $21
	.word @song3ref123
	.byte $41, $39
	.word @song3ref109
	.byte $41, $2c
	.word @song3ref123
	.byte $41, $2c
	.word @song3ref123
	.byte $41, $21
	.word @song3ref123
	.byte $41, $39
	.word @song3ref109
	.byte $41, $2c
	.word @song3ref123
	.byte $41, $2c
	.word @song3ref123
	.byte $41, $21
	.word @song3ref123
	.byte $9d, $84, $25, $85, $24, $85, $25, $81, $25, $81, $24, $81, $25, $81, $00, $85, $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d
	.byte $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03, $8d
	.byte $03, $8d, $03, $8d, $03, $8d, $03, $8d, $03
@song3ref299:
	.byte $9d, $06, $85, $05, $85, $06, $81, $06, $81, $05, $81, $06, $81
@song3ref312:
	.byte $03, $8d, $04, $89, $06, $81, $03, $8d, $04, $8d, $03, $8d, $04, $89, $06, $81, $03, $81, $06, $89, $04, $8d, $03, $8d
	.byte $04, $89, $06, $81, $03, $8d, $04, $8d, $03, $8d, $04, $89, $06, $81, $03, $81, $06, $89, $04, $8d
	.byte $41, $2c
	.word @song3ref312
	.byte $41, $2c
	.word @song3ref312
	.byte $41, $21
	.word @song3ref312
	.byte $41, $39
	.word @song3ref299
	.byte $41, $2c
	.word @song3ref312
	.byte $41, $2c
	.word @song3ref312
	.byte $41, $21
	.word @song3ref312
	.byte $41, $39
	.word @song3ref299
	.byte $41, $2c
	.word @song3ref312
	.byte $41, $2c
	.word @song3ref312
	.byte $41, $21
	.word @song3ref312
	.byte $9d, $06, $85, $05, $85, $06, $81, $06, $81, $05, $81, $06, $81, $00, $85, $42
	.word @song3ch4loop
@song3ch5:
@song3ch5loop:
	.byte $ff, $ff, $ff, $ff, $78, $80
@song3ref414:
	.byte $40, $5a, $81, $7a, $40, $5a, $81, $7c, $82, $40, $5a, $89, $7a, $80, $40, $5a, $81, $7c, $82, $40, $5a, $81, $7a, $80
	.byte $40, $5a, $81, $78, $40, $5a, $81, $7a, $40, $5a, $81, $7c, $82, $40, $5a, $89, $7a, $80, $40, $5a, $81, $7c, $82, $40
	.byte $5a, $81, $7a, $80, $40, $5a, $81, $78, $40, $5a, $81, $7a, $40, $5a, $81, $7c, $82, $40, $5a, $89, $7a, $80, $40, $5a
	.byte $81, $7c, $82, $40, $5a, $81, $7a, $80, $40, $5a, $81, $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $23
	.word @song3ref414
	.byte $c1, $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $23
	.word @song3ref414
	.byte $c1, $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $24
	.word @song3ref414
	.byte $78
	.byte $41, $23
	.word @song3ref414
	.byte $c1, $00, $85, $42
	.word @song3ch5loop
@song3ch6:
@song3ch6loop:
	.byte $00, $ff, $fd, $ff, $ff, $7e, $51, $fe, $10, $8c, $25, $bd, $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd
	.byte $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd, $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd
	.byte $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd, $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd
	.byte $7f, $00, $ff, $bd, $ff, $ff, $00, $85, $42
	.word @song3ch6loop
@song3ch7:
@song3ch7loop:
@song3ref706:
	.byte $00, $81, $79, $80
@song3ref710:
	.byte $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81, $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81, $25, $81, $7c, $25
	.byte $81, $79, $25, $81, $00, $81, $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $1e
	.word @song3ref710
	.byte $71, $51, $02, $d0, $8c, $25, $8d, $25, $ab, $81
	.byte $41, $22
	.word @song3ref706
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $1e
	.word @song3ref710
	.byte $71, $51, $02, $d0, $8c, $25, $8d, $25, $ab, $81
	.byte $41, $22
	.word @song3ref706
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $1e
	.word @song3ref710
	.byte $71, $51, $02, $d0, $8c, $25, $8d, $25, $ab, $81
	.byte $41, $22
	.word @song3ref706
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $20
	.word @song3ref710
	.byte $41, $1e
	.word @song3ref710
	.byte $71, $51, $02, $d0, $8c, $25, $8d, $25, $ab, $81, $00, $85, $42
	.word @song3ch7loop
@song3ch8:
@song3ch8loop:
	.byte $78, $a2
@song3ref951:
	.byte $17, $81, $7f, $17, $81, $17, $81, $17, $81, $78, $17, $81, $7f, $17, $81, $17, $81, $17, $81, $78, $17, $81, $7f, $17
	.byte $81, $17, $81, $17, $81, $78, $17, $81, $7f, $17, $81, $17, $81, $17, $81, $78
	.byte $41, $20
	.word @song3ref951
@song3ref994:
	.byte $78, $15, $81, $7f, $15, $81, $15, $81, $15, $81, $78, $15, $81, $7f, $15, $81, $15, $81, $15, $81, $78, $15, $81, $7f
	.byte $15, $81, $15, $81, $15, $81, $78, $15, $81, $7f, $15, $81, $15, $81, $15
@song3ref1033:
	.byte $81, $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81, $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81, $78, $12, $81
	.byte $7f, $12, $81, $12, $81, $12, $81, $78, $12, $81, $7f, $12, $81, $12, $81, $12, $81, $78
	.byte $41, $20
	.word @song3ref951
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $78, $1a, $81, $7f, $1a, $81, $1a, $81, $1a, $81, $78, $1a, $81, $7f, $1a, $81, $1a, $81, $1a, $81, $78, $1a, $81, $7f
	.byte $1a, $81, $1a, $81, $1a, $81, $78, $1a, $81, $7f, $1a, $81, $1a, $81, $1a
	.byte $41, $21
	.word @song3ref1033
	.byte $78
	.byte $41, $20
	.word @song3ref951
@song3ref1128:
	.byte $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81, $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81, $78, $13, $81, $7f
	.byte $13, $81, $13, $81, $13, $81, $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81
	.byte $41, $20
	.word @song3ref994
@song3ref1171:
	.byte $78, $12, $81, $7f, $12, $81, $12, $81, $12, $81, $78, $12, $81, $7f, $12, $81, $12, $81, $12, $81, $78, $12, $81, $7f
	.byte $12, $81, $12, $81, $12, $81, $78, $12, $81, $7f, $12, $81, $12, $81, $12, $81, $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $78
	.byte $41, $20
	.word @song3ref951
	.byte $41, $20
	.word @song3ref1128
	.byte $41, $20
	.word @song3ref994
	.byte $41, $20
	.word @song3ref1171
	.byte $00, $85, $42
	.word @song3ch8loop
@song3ch9:
@song3ch9loop:
@song3ref1360:
	.byte $94, $23, $8d, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $85, $23, $8d, $2a, $85, $28, $81, $2a, $85, $26
	.byte $89, $25, $85, $26, $85, $21, $8d, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $85, $1f
@song3ref1404:
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $25, $85, $26, $85
@song3ref1417:
	.byte $23, $8d, $2f, $85, $2d, $81, $2f, $85, $2a, $89, $28, $85, $2a, $85, $23, $8d, $32, $85, $31, $81, $32, $85, $2f, $89
	.byte $2d, $85, $2f, $85, $26, $8d, $32, $85, $31, $81, $2d, $85, $26, $89, $25, $85, $26, $85, $1f, $8d, $2b, $85, $2a, $81
	.byte $2b
@song3ref1466:
	.byte $85, $2a, $89, $28, $85, $2a, $85
@song3ref1473:
	.byte $23, $8d, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $85, $1f, $8d, $2b, $85, $2a, $81, $2b, $85, $26, $89
	.byte $25, $85, $26, $85, $21, $8d, $28, $85, $26, $81, $28, $85, $25, $89, $23, $85, $25, $85, $1e
	.byte $41, $35
	.word @song3ref1404
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song3ref1466
	.byte $41, $35
	.word @song3ref1404
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song3ref1466
	.byte $41, $35
	.word @song3ref1404
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song3ref1466
	.byte $41, $35
	.word @song3ref1404
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song3ref1466
	.byte $41, $35
	.word @song3ref1404
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song3ref1466
	.byte $41, $35
	.word @song3ref1404
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $85, $2a, $85, $00, $85, $42
	.word @song3ch9loop
@song3ch10:
@song3ch10loop:
	.byte $7c, $00, $8d, $94
@song3ref1620:
	.byte $23, $85, $21, $81, $23, $85, $1e, $89, $1c, $85, $1e, $95, $26, $85, $25, $81, $26, $85, $23, $89, $21, $85, $23, $95
	.byte $26, $85, $25, $81, $21, $85, $1a, $89, $19, $85, $1a, $95, $1f, $85, $1e, $81, $1f, $85, $1e, $89, $1c, $85, $1e, $85
	.byte $8f, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $95, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26
	.byte $95, $2a, $85, $28, $81, $2a, $85, $23, $89, $21, $85, $23, $95, $28, $85, $26, $81, $28, $85, $26, $89, $25, $85, $26
	.byte $85, $00, $8d
	.byte $41, $1e
	.word @song3ref1620
@song3ref1722:
	.byte $1e, $89, $1c, $85, $1e, $95, $1f, $85, $1e, $81, $1f, $89, $1e, $85, $1c, $85, $1e, $85, $00, $8d, $2a, $85, $28, $81
	.byte $2a, $85, $26, $89, $25, $85, $26, $95, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $95, $2a, $85, $28, $81
	.byte $26, $85, $21, $89, $1f, $85, $1c, $95, $26, $85, $25, $81, $28, $85, $26, $89, $25, $85, $26, $85, $00, $8d
	.byte $41, $1e
	.word @song3ref1620
	.byte $41, $46
	.word @song3ref1722
	.byte $41, $1e
	.word @song3ref1620
	.byte $41, $46
	.word @song3ref1722
	.byte $41, $1e
	.word @song3ref1620
	.byte $41, $46
	.word @song3ref1722
	.byte $41, $1e
	.word @song3ref1620
	.byte $41, $46
	.word @song3ref1722
	.byte $41, $1e
	.word @song3ref1620
	.byte $41, $45
	.word @song3ref1722
	.byte $85, $42
	.word @song3ch10loop
@song3ch11:
@song3ch11loop:
	.byte $79, $00, $8d
	.byte $41, $6c
	.word @song3ref1360
	.byte $00, $8d
	.byte $41, $2b
	.word @song3ref1473
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song3ref1417
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song3ref1473
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song3ref1417
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song3ref1473
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song3ref1417
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song3ref1473
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song3ref1417
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song3ref1473
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song3ref1417
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song3ref1473
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song3ref1417
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $00, $85, $42
	.word @song3ch11loop
@song3ch12:
@song3ch12loop:
	.byte $00, $ff, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
@song3ref2039:
	.byte $87, $00, $9d
@song3ref2042:
	.byte $7f, $90, $23, $81, $7b, $23, $85, $7f, $23, $81, $7b, $23, $85, $7c, $23, $81, $78, $23, $85, $79, $23, $81, $75, $23
	.byte $89, $00, $a9, $7f, $21, $81, $79, $21, $85, $7f, $21, $81, $7c, $21, $81, $21, $85, $79, $21, $81, $21, $85, $76, $21
	.byte $81, $21, $89, $7f, $8a, $1e, $89, $7c, $1e, $89, $79, $1e, $89, $76, $1e, $89, $00, $8d, $a7
	.byte $41, $29
	.word @song3ref2042
	.byte $81, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81
	.byte $41, $32
	.word @song3ref2039
	.byte $41, $29
	.word @song3ref2042
	.byte $81, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $87, $7f
@song3ref2142:
	.byte $25, $85, $26, $81, $25, $85, $26, $89, $1e, $81, $1e, $81, $25, $85, $26, $81, $26, $81, $25, $89, $23, $85, $1f, $85
	.byte $1e, $81, $1f, $a5, $23, $85, $25, $81, $23, $85, $25, $89, $1c, $81, $1c, $81, $23, $85, $25, $81, $25, $81, $23, $89
	.byte $22, $85, $1e, $85, $1c, $81, $1e, $85, $1e, $81, $1e, $81, $23, $85, $25, $81, $26, $81, $87
@song3ref2209:
	.byte $28, $85, $2a, $81, $28, $85, $2a, $89, $23, $81, $23, $81, $2a, $85, $2d, $81, $2d, $81, $2d, $85, $2d, $81, $2b, $85
	.byte $2b, $85, $2a, $81, $2b, $9d, $26, $81, $25, $81, $26, $85, $28, $85, $21, $85, $28, $85, $21, $85, $28, $85, $2b, $81
	.byte $2b, $81, $2b, $89, $2a, $85, $2a, $85, $28, $81, $2a, $85, $21, $85, $26, $85, $25, $81, $23, $81, $87
@song3ref2278:
	.byte $31, $85, $32, $81, $31, $85, $32, $89, $2a, $81, $2a, $81, $31, $85, $32, $81, $32, $81, $31, $89, $2f, $85, $2b, $85
	.byte $2a, $81, $2b, $a5, $2f, $85, $31, $81, $2f, $85, $31, $89, $28, $81, $28, $81, $2f, $85, $31, $81, $31, $81, $2f, $89
	.byte $2e, $85, $2a, $85, $28, $81, $2a, $85, $2a, $81, $2a, $81, $2f, $85, $31, $81, $32, $81, $87
@song3ref2345:
	.byte $34, $85, $36, $81, $34, $85, $36, $89, $2f, $81, $2f, $81, $36, $85, $39, $81, $39, $81, $39, $85, $39, $81, $37, $85
	.byte $37, $85, $36, $81, $37, $9d, $32, $81, $31, $81, $32, $85, $34, $85, $2d, $85, $34, $85, $2d, $85, $34, $85, $37, $81
	.byte $37, $81, $37, $89, $36, $85, $36, $85, $34, $81, $36, $9d, $00, $85, $42
	.word @song3ch12loop
@song3ch13:
@song3ch13loop:
	.byte $00, $ff, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $b7, $7f, $8a
@song3ref2427:
	.byte $2d, $81, $2f, $85, $7c, $2d, $81, $2f, $85, $79, $2d, $81, $2f, $85, $76, $2d, $81, $2f, $a9, $79, $23, $81, $25, $85
	.byte $7f, $23, $81, $25, $85, $7c, $23, $81, $25, $85, $79, $23, $81, $25, $85, $76, $23, $81, $25, $85, $73, $23, $81, $25
	.byte $81, $7f, $28, $85, $26, $81, $28, $85, $79, $26, $81, $28, $85, $73, $25, $81, $26, $81, $26, $81, $26, $81, $b7, $7f
	.byte $41, $23
	.word @song3ref2427
	.byte $8d, $7f, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $85, $2a, $85, $b7
	.byte $41, $3b
	.word @song3ref2427
	.byte $7f
	.byte $41, $23
	.word @song3ref2427
	.byte $8d, $7f, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $85, $2a, $85, $8f, $79
	.byte $41, $41
	.word @song3ref2142
	.byte $89
	.byte $41, $43
	.word @song3ref2209
	.byte $89
	.byte $41, $41
	.word @song3ref2278
	.byte $89
	.byte $41, $3b
	.word @song3ref2345
	.byte $95, $00, $85, $42
	.word @song3ch13loop
@song4ch0:
	.byte $46, $03
@song4ch0loop:
@song4ref4:
	.byte $bf
@song4ref5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0c
	.word @song4ref5
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song4ch0loop
@song4ch19:
@song4ch18:
@song4ch17:
@song4ch16:
@song4ch15:
@song4ch14:
@song4ch12:
@song4ch5:
@song4ch2:
@song4ch1:
@song4ch1loop:
	.byte $41, $0d
	.word @song4ref4
	.byte $41, $0c
	.word @song4ref5
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song4ch1loop
@song4ch3:
@song4ch3loop:
	.byte $bf, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $8f, $86
@song4ref66:
	.byte $25, $85, $00, $95, $25, $8d, $00, $8d, $25, $85, $00, $95, $25, $8d, $00, $8d
	.byte $41, $0f
	.word @song4ref66
	.byte $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $bf, $ff, $ff, $ff, $ff
@song4ref105:
	.byte $01, $95, $01, $8d, $01, $95, $01, $95, $01, $81, $01, $89, $01, $95
	.byte $41, $0e
	.word @song4ref105
	.byte $41, $0e
	.word @song4ref105
	.byte $01, $95, $01, $8d, $01, $95, $01, $bd
@song4ref133:
	.byte $01, $8d, $02, $85, $01, $8d, $01, $85, $02, $8d, $01, $8d, $02, $85, $01, $81, $01, $89, $01, $85, $02, $8d
	.byte $41, $16
	.word @song4ref133
	.byte $00, $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song4ch4loop
@song4ch6:
@song4ch6loop:
	.byte $bf, $ff, $ff, $ff, $ff, $ff, $ef, $7d, $86, $25, $25, $25, $25, $25, $25, $25, $25, $00, $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song4ch6loop
@song4ch7:
@song4ch7loop:
	.byte $bf, $7c, $86, $25, $85, $7f, $25, $85, $88, $25, $85, $86, $25, $85, $7c, $25, $85, $7f, $25, $81, $7c, $84, $25, $81
	.byte $7f, $88, $25, $81, $7c, $84, $25, $81, $7f, $86, $25, $85, $7c
@song4ref248:
	.byte $25, $81, $84, $25, $81, $7f, $86, $25, $81, $7c, $84, $25, $81, $7f, $88, $25, $81, $7c, $84, $25, $81, $7f, $86, $25
	.byte $81, $7c, $84, $25, $81, $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
@song4ref293:
	.byte $86, $25, $81, $84, $25, $81, $7f, $86, $25, $81, $92, $25, $81, $88, $25, $81, $7c, $84, $25, $81, $7f, $86, $25, $81
	.byte $7c, $84, $25, $81, $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $41, $10
	.word @song4ref293
	.byte $86, $25, $81, $84, $25, $81, $7f, $86, $25, $81, $7c, $84, $25, $81, $7f, $88, $25, $85
@song4ref370:
	.byte $86, $25, $85, $25, $81, $84, $25, $81, $86, $25, $81, $7c, $84, $25, $81, $7f, $88, $25, $81, $7c, $84, $25, $81, $7f
	.byte $41, $0e
	.word @song4ref370
	.byte $7f, $86, $25, $81, $7c, $84, $25, $81, $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $86
	.byte $41, $10
	.word @song4ref248
	.byte $41, $10
	.word @song4ref293
	.byte $00, $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song4ch7loop
@song4ch8:
@song4ch8loop:
	.byte $bf, $9c
@song4ref446:
	.byte $14, $89, $14, $89, $14, $85
@song4ref452:
	.byte $17, $89, $17, $89, $17, $85, $19, $89, $19, $89, $19, $85, $1b, $89, $1b, $89, $1b, $85
	.byte $41, $18
	.word @song4ref446
	.byte $41, $18
	.word @song4ref446
@song4ref476:
	.byte $19, $89, $19, $89, $19, $85, $17, $89, $17, $89, $17
@song4ref487:
	.byte $85, $14, $89, $14, $89, $14, $85, $14, $89, $14, $89, $14, $85
	.byte $41, $18
	.word @song4ref446
	.byte $41, $18
	.word @song4ref446
	.byte $41, $18
	.word @song4ref446
	.byte $41, $0c
	.word @song4ref476
	.byte $16, $89, $16, $89, $16
	.byte $41, $0d
	.word @song4ref487
	.byte $41, $12
	.word @song4ref452
	.byte $41, $18
	.word @song4ref446
	.byte $41, $18
	.word @song4ref446
	.byte $41, $18
	.word @song4ref476
	.byte $41, $18
	.word @song4ref446
	.byte $41, $18
	.word @song4ref446
	.byte $41, $18
	.word @song4ref446
	.byte $41, $18
	.word @song4ref476
	.byte $00, $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $42
	.word @song4ch8loop
@song4ch9:
@song4ch9loop:
	.byte $bf, $7c, $9e
@song4ref557:
	.byte $14, $89, $14, $89, $00, $a5, $19, $85, $00, $8d, $19, $00, $14, $00, $19, $85, $19, $81, $1b, $89, $1b, $85
	.byte $41, $10
	.word @song4ref557
@song4ref582:
	.byte $1b, $00, $83, $1b, $00, $83, $1b, $00, $83, $14, $89, $14, $89, $00, $a5, $19, $95, $19, $00, $14, $00, $19, $85, $19
	.byte $81, $1b, $89, $1b, $81, $20, $81, $19, $89, $19, $8d, $19, $00, $19, $00, $83, $19, $00, $8b, $17, $00, $83, $14, $89
	.byte $14, $91, $14, $89, $14, $91
	.byte $41, $16
	.word @song4ref557
	.byte $41, $10
	.word @song4ref557
	.byte $41, $2e
	.word @song4ref582
	.byte $16, $89, $16, $91, $14, $89, $14, $91
	.byte $41, $16
	.word @song4ref557
	.byte $41, $10
	.word @song4ref557
	.byte $41, $36
	.word @song4ref582
	.byte $41, $16
	.word @song4ref557
	.byte $41, $10
	.word @song4ref557
	.byte $41, $2e
	.word @song4ref582
	.byte $16, $89, $16, $91, $14, $89, $14, $91, $00, $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $42
	.word @song4ch9loop
@song4ch10:
@song4ch10loop:
	.byte $bf, $98
@song4ref691:
	.byte $2c, $95, $5c, $a5, $2e, $85, $5c, $8d, $2e, $85, $5c, $9d
	.byte $41, $0c
	.word @song4ref691
@song4ref706:
	.byte $2c, $95, $5c, $a5, $36, $89, $5c, $89, $33, $85, $5c, $9d
@song4ref718:
	.byte $2c, $95, $5c, $a5, $2e, $8d, $2a, $8d, $2c, $8d, $5c, $8d
	.byte $41, $0c
	.word @song4ref691
	.byte $41, $0c
	.word @song4ref691
@song4ref736:
	.byte $2c, $95, $5c, $a5, $38, $89, $5c, $89, $35, $85, $5c, $8d, $31, $8d
	.byte $41, $0c
	.word @song4ref718
	.byte $41, $0c
	.word @song4ref691
	.byte $41, $0c
	.word @song4ref691
	.byte $41, $18
	.word @song4ref706
	.byte $41, $0c
	.word @song4ref691
	.byte $41, $0c
	.word @song4ref691
	.byte $41, $0e
	.word @song4ref736
	.byte $41, $0c
	.word @song4ref718
	.byte $00, $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $42
	.word @song4ch10loop
@song4ch11:
@song4ch11loop:
	.byte $bf, $00, $9d, $98
@song4ref788:
	.byte $33, $95, $5c, $95, $2a, $85, $5c, $85, $36, $8d, $5c, $ad, $33, $95, $5c, $95, $2a, $85, $5c, $85, $31, $8d, $5c, $8d
	.byte $9f, $33, $95, $5c, $91, $35, $89, $5c, $85, $31, $9d, $5c, $9d, $33, $95, $5c, $95, $31, $8d, $5c, $9d, $00, $9d
	.byte $41, $1d
	.word @song4ref788
@song4ref838:
	.byte $36, $89, $5c, $85, $33, $8d, $5c, $ad, $33, $95, $5c, $95, $31, $8d, $5c, $9d, $00, $9d
	.byte $41, $2f
	.word @song4ref788
	.byte $41, $1d
	.word @song4ref788
	.byte $41, $11
	.word @song4ref838
	.byte $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $42
	.word @song4ch11loop
@song4ch13:
@song4ch13loop:
	.byte $bf, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00, $8d, $ac
@song4ref886:
	.byte $2c, $5c, $2c, $5c, $50, $a8, $38, $2c, $43, $20, $83, $00, $85, $20, $81, $5c, $81, $2c, $5c, $2c, $5c, $20, $85, $00
	.byte $85, $20, $00, $93, $33, $81, $31, $5c, $2f, $81, $2c, $81, $2a, $81, $2c, $5c, $27, $81, $2a, $81, $2c, $81, $5c, $81
	.byte $00, $85, $2c, $5c, $2c, $5c, $20, $85, $5c, $81, $20, $81, $2c, $5c, $83, $2c, $5c, $2c, $5c, $20, $5c, $20, $5c, $2c
	.byte $81, $5c, $81, $20, $5c, $83, $2c, $81, $5c, $81, $20, $5c, $83, $31, $81, $33, $5c, $2f, $81, $2c, $5c, $2a, $81, $27
	.byte $5c, $50, $0c, $3a, $3b, $43, $2f, $83
@song4ref990:
	.byte $2c, $81, $5c, $81, $20, $5c, $20, $5c, $20, $5c, $20, $5c, $20, $5c, $20, $5c, $87
	.byte $41, $0c
	.word @song4ref990
	.byte $2c, $81, $5c, $81, $20, $81, $5c, $81, $20, $5c, $20, $5c, $20, $81, $5c, $81, $31, $5c, $2f, $5c
	.byte $41, $0c
	.word @song4ref990
	.byte $31, $85, $25, $5c, $83, $2f, $85, $23, $5c, $83, $31, $5c, $31, $5c, $20, $5c, $23, $5c, $2f, $81, $31, $5c, $33, $5c
	.byte $36, $5c, $38, $81, $5c, $91, $33, $83, $5c, $36, $81, $3a, $5c, $83, $36, $5c, $20, $85, $38, $5c, $83, $00, $8d
	.byte $41, $60
	.word @song4ref886
	.byte $00, $ff, $fd
	.byte $41, $0c
	.word @song4ref5
	.byte $ff, $ff, $42
	.word @song4ch13loop
@song5ch0:
	.byte $46, $0a
@song5ch0loop:
	.byte $9f, $9f, $42
	.word @song5ch0loop
@song5ch19:
@song5ch18:
@song5ch17:
@song5ch16:
@song5ch15:
@song5ch14:
@song5ch13:
@song5ch12:
@song5ch11:
@song5ch10:
@song5ch9:
@song5ch8:
@song5ch7:
@song5ch6:
@song5ch5:
@song5ch3:
@song5ch2:
@song5ch1:
@song5ch1loop:
	.byte $9f, $9f, $42
	.word @song5ch1loop
@song5ch4:
@song5ch4loop:
	.byte $03, $04, $06, $00, $01, $02, $00, $91, $9f, $42
	.word @song5ch4loop
